import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import Report from "@/types/report";

const ViewReportDialog = ({ report }: { report: Report }) => {
  if (!report)
    return (
      <Dialog>
        <DialogTrigger asChild>
          <Button variant="outline" className="rounded-xl shadow-md px-4 py-2">
            View Report
          </Button>
        </DialogTrigger>
        <DialogContent className="max-w-2xl rounded-2xl p-6 shadow-xl">
          <DialogHeader>
            <DialogTitle asChild>
              <h2 className="font-extrabold text-center text-2xl text-gray-800">
                Report Not Found
              </h2>
            </DialogTitle>
          </DialogHeader>
        </DialogContent>
      </Dialog>
    );

  return (
    <Dialog>
      <DialogTrigger asChild>
        <Button variant="outline" className="rounded-xl shadow-md px-4 py-2">
          View Report
        </Button>
      </DialogTrigger>
      <DialogContent className="max-w-2xl rounded-2xl p-6 shadow-xl">
        <DialogHeader>
          <DialogTitle asChild>
            <h2 className="font-extrabold text-center text-2xl text-gray-800">
              🩺 Medical AI Voice Agent Report
            </h2>
          </DialogTitle>
        </DialogHeader>

        <div className="mt-6 max-h-[70vh] overflow-y-auto pr-2 space-y-5 text-gray-700">
          <div className="border rounded-xl p-4 shadow-sm">
            <h3 className="font-semibold text-blue-600 text-lg mb-2">
              Session Info
            </h3>
            <div className="grid grid-cols-2 gap-2 text-sm">
              <p>
                <span className="font-medium">Agent:</span> {report.agent}
              </p>
              <p>
                <span className="font-medium">Patient:</span> {report.user}
              </p>
              <p className="col-span-2">
                <span className="font-medium">Consulted On:</span>
                {new Date(report.timestamp).toLocaleString()}
              </p>
            </div>
          </div>

          <div className="border rounded-xl p-4 shadow-sm">
            <h3 className="font-semibold text-blue-600 text-lg mb-2">
              Chief Complaint
            </h3>
            <p>{report.chiefComplaint}</p>
          </div>

          <div className="border rounded-xl p-4 shadow-sm">
            <h3 className="font-semibold text-blue-600 text-lg mb-2">
              Summary
            </h3>
            <p>{report.summary}</p>
          </div>

          <div className="border rounded-xl p-4 shadow-sm">
            <h3 className="font-semibold text-blue-600 text-lg mb-2">
              Symptoms
            </h3>
            <ul className="list-disc pl-5 space-y-1">
              {report.symptoms.map((symptom, index) => (
                <li key={index}>{symptom.toUpperCase()}</li>
              ))}
            </ul>
          </div>

          <div className="border rounded-xl p-4 shadow-sm">
            <h3 className="font-semibold text-blue-600 text-lg mb-2">
              Duration & Severity
            </h3>
            <div className="grid grid-cols-2 gap-2 text-sm">
              <p>
                <span className="font-medium">Duration:</span> {report.duration}
              </p>
              <p>
                <span className="font-medium">Severity:</span> {report.severity}
              </p>
            </div>
          </div>

          <div className="border rounded-xl p-4 shadow-sm">
            <h3 className="font-semibold text-blue-600 text-lg mb-2">
              Medications Mentioned
            </h3>
            <ul className="list-disc pl-5 space-y-1">
              {report.medicationsMentioned.map((medication, index) => (
                <li key={index}>{medication}</li>
              ))}
            </ul>
          </div>

          <div className="border rounded-xl p-4 shadow-sm">
            <h3 className="font-semibold text-blue-600 text-lg mb-2">
              Recommendations
            </h3>
            <ul className="list-disc pl-5 space-y-1">
              {report.recommendations.map((recommendation, index) => (
                <li key={index}>{recommendation}</li>
              ))}
            </ul>
          </div>
        </div>

        <DialogFooter>
          <p className="text-xs text-center text-gray-500">
            ⚠️ This report was generated by an AI Medical Assistant for
            informational purposes only.
          </p>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default ViewReportDialog;
